### ISSUE TITLE
Add argument for GPIO slowdown

### ISSUE THREAD

**Issue by briankennedy1** [dannielum/cactuspi-client#1]
Raspberry Pi 4 is a bit too speedy and the default output is garbage if you don't use the "--led-slowdown-gpio" argument with a value of "4". Might be worth adding into the default config.json!

**Comment by dannielum** [comment]
Thanks for the tips. Since everyone might have slightly different hardware setup for the projects, I do expect people will need to play around a bit with the configurations. Since I don't have the setup for Raspberry Pi 4, I decide not to put in the support without being able to test it. But I will be happy to review and merge it if you want to create a PR for it.
